version: '3'
services:
  db:
    container_name: todo_db
    image: postgres:10.7
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./init-users-db.sh:/docker-entrypoint-initdb.d/init-users-db.sh
    ports:
      - '5445:5432'
